exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "notebooks",
]

line-length = 88
indent-width = 4

target-version = "py312"

[lint]
preview = true
select = [
    "A",
    "ANN",
    "ARG",
    "B",
    "C4",
    "COM",
    "E",
    "F",
    "FAST",
    "FURB",
    "I",
    "N",
    "NPY",
    "PD",
    "PERF",
    "PIE",
    "PL",
    "PYI",
    "PT",
    "Q",
    "RET",
    "RUF",
    "S",
    "SLF",
    "TID",
    "UP",
    "W",
]
ignore = [
    "B904",
    "COM812",
    "I001",
    "N818",
    "UP035",
]

fixable = ["ALL"]
unfixable = []

[lint.per-file-ignores]
"**/infrastructure/*_router.py" = ["ANN201"]
"app/document/domain/document.py" = ["RUF012"]
"app/document/domain/chunk.py" = ["RUF012"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

docstring-code-format = false
docstring-code-line-length = "dynamic"
